### ISSUE TITLE
Webpack 4 compatibility

### ISSUE THREAD

**Issue by Tronix117** [nativescript-vue/nativescript-vue-target#1]
There is some deprecations triggering errors on Webpack 4

```
(node:15354) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at Object.apply (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:29:16)
    at Object.nativescriptTarget (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:15:14)
    at Object.module.exports [as target] (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:25:32)
    at WebpackOptionsApply.process (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/lib/WebpackOptionsApply.js:198:12)
    at webpack (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/lib/webpack.js:42:48)
    at processOptions (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/bin/webpack.js:157:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:15354) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at NsNodeGlobalsPlugin.apply (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/lib/NsNodeGlobalsPlugin.js:8:14)
    at Compiler.apply (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/tapable/lib/Tapable.js:71:16)
    at Compiler.deprecated [as apply] (internal/util.js:47:15)
    at Object.apply (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:29:16)
    at Object.nativescriptTarget (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:15:14)
    at Object.module.exports [as target] (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/nativescript-vue-target/index.js:25:32)
    at WebpackOptionsApply.process (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/lib/WebpackOptionsApply.js:198:12)
    at webpack (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/lib/webpack.js:42:48)
    at processOptions (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeremyt/Development/Wikodit/MIRA-Mira/mira-mobile/node_modules/webpack/bin/webpack.js:157:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

**Comment by maxorlovsky** [comment]
Project dead? @rigor789 @lewebsimple

**Comment by maxorlovsky** [comment]
I've opened a PR in case this repo is still maintained https://github.com/nativescript-vue/nativescript-vue-target/pull/2

**Comment by rigor789** [comment]
Hey @maxorlovsky this is currently used in [vue-cli-template](https://github.com/nativescript-vue/vue-cli-template) which is using webpack 3.

The [next branch of the vue-cli-template](https://github.com/nativescript-vue/vue-cli-template/tree/next) is using webpack 4 and `nativescript-vue-target` is no longer required.

We are soon going to merge the next branch into master along with the 2.0 release of nativescript-vue this month. I would consider this project dead at this point as it's no longer needed, only by the older vue-cli-template (current master) which it works with.

**Comment by maxorlovsky** [comment]
I'm integrating nativescript-vue into existing project. I'm not using nativescript-vue. But first test project I've built using cli, so I'm curious. Do I need this package to run nativescript-vue? Or I should run nativescript-dev-webpack directly?
I guess late oner, as this one is discontinued. Or is there a completely different way to do it, which is more correct?

**Comment by rigor789** [comment]
The next branch of the vue-cli-template uses nativescript-dev-webpack, and that is the preferred way at the moment, since it works a lot more reliably than the previous version.

**Comment by maxorlovsky** [comment]
Ok, thank you very much. Will use that instead then :)

**Comment by maxorlovsky** [comment]
Also, might be a good idea to update readme of this project and archive it. As google results point to this repo.
